<template>
  <section class="prose max-w-none">
    <h1>All features</h1>
    <ul class="mt-4">
      <li><NuxtLink to="/features/abTesting">A/B Testing</NuxtLink></li>
      <li><NuxtLink to="/features/activeChatbots">Active chatbots</NuxtLink></li>
      <li><NuxtLink to="/features/additionalAgentPrice">Additional Agents (per month)</NuxtLink></li>
      <li><NuxtLink to="/features/adobeCommerce">Adobe Commerce</NuxtLink></li>
      <li><NuxtLink to="/features/advancedButtonActions">Advanced Button Actions</NuxtLink></li>
      <li><NuxtLink to="/features/agentsIncluded">Agents Included</NuxtLink></li>
      <li><NuxtLink to="/features/aiAgent">AI Agent</NuxtLink></li>
      <li><NuxtLink to="/features/aiAnswers">AI-generated Answers</NuxtLink></li>
      <li><NuxtLink to="/features/aiAssist">AI Assist</NuxtLink></li>
      <li><NuxtLink to="/features/aiBlocks">AI-agent Blocks</NuxtLink></li>
      <li><NuxtLink to="/features/aiConversationsQuota">AI Conversations Quota</NuxtLink></li>
      <li><NuxtLink to="/features/aiKnowledge">AI Knowledge Training</NuxtLink></li>
      <li><NuxtLink to="/features/aiModelTraining">AI Model Training</NuxtLink></li>
      <li><NuxtLink to="/features/aiSpam">AI Inbox Spam Filter</NuxtLink></li>
      <li><NuxtLink to="/features/aiTriggers">AI-based Triggers</NuxtLink></li>
      <li><NuxtLink to="/features/aiUsage">AI Usage</NuxtLink></li>
      <li><NuxtLink to="/features/aiWriting">AI Writing Assistant</NuxtLink></li>
      <li><NuxtLink to="/features/allChats">All chats</NuxtLink></li>
      <li><NuxtLink to="/features/allMessages">All messages</NuxtLink></li>
      <li><NuxtLink to="/features/allUsers">All users</NuxtLink></li>
      <li><NuxtLink to="/features/apiAnalytics">API Analytics</NuxtLink></li>
      <li><NuxtLink to="/features/apiAutomation">Automation via APIs</NuxtLink></li>
      <li><NuxtLink to="/features/auditLogs">Audit Logs</NuxtLink></li>
      <li><NuxtLink to="/features/automaticBotBuilding">Automatic Bot Building</NuxtLink></li>
      <li><NuxtLink to="/features/automaticDataRemoval">Automatic data removal</NuxtLink></li>
      <li><NuxtLink to="/features/automationQuota">Automation Quota (visitors/month)</NuxtLink></li>
      <li><NuxtLink to="/features/autoTags">Auto-tagging Of Conversations</NuxtLink></li>
      <li><NuxtLink to="/features/avChat">Video & Audio chat</NuxtLink></li>
      <li><NuxtLink to="/features/averageMessages">Average messages</NuxtLink></li>
      <li><NuxtLink to="/features/banning">Visitor Banning</NuxtLink></li>
      <li><NuxtLink to="/features/bigCommerce">BigCommerce</NuxtLink></li>
      <li><NuxtLink to="/features/billableConversations">Billable Conversations Limit</NuxtLink></li>
      <li><NuxtLink to="/features/busiestPeriod">Busiest period</NuxtLink></li>
      <li><NuxtLink to="/features/businessRulesAnalysis">Business Rules Analysis</NuxtLink></li>
      <li><NuxtLink to="/features/cannedResponses">Canned Responses</NuxtLink></li>
      <li><NuxtLink to="/features/chatEventTracking">Chat Events Tracking (GA)</NuxtLink></li>
      <li><NuxtLink to="/features/chatSDKs">Chat SDKs</NuxtLink></li>
      <li><NuxtLink to="/features/chatsPackage">Chats Package</NuxtLink></li>
      <li><NuxtLink to="/features/chatWidget">Chat widget</NuxtLink></li>
      <li><NuxtLink to="/features/chatWindowDocking">Chat Window Docking</NuxtLink></li>
      <li><NuxtLink to="/features/cloudBased">Cloud-based</NuxtLink></li>
      <li><NuxtLink to="/features/conditionalFlows">Conditional Flows</NuxtLink></li>
      <li><NuxtLink to="/features/contactForm">Contact Form</NuxtLink></li>
      <li><NuxtLink to="/features/crmCustomAttrs">Custom Attributes</NuxtLink></li>
      <li><NuxtLink to="/features/crmLifecycle">Customer Lifecycle Tracking</NuxtLink></li>
      <li><NuxtLink to="/features/crmNotes">Customer-based Notes</NuxtLink></li>
      <li><NuxtLink to="/features/crmProfile">Customer Profile</NuxtLink></li>
      <li><NuxtLink to="/features/crmSegmentation">Customer Segmentation</NuxtLink></li>
      <li><NuxtLink to="/features/crmSmartFilters">Smart Filters</NuxtLink></li>
      <li><NuxtLink to="/features/crmTimeline">Customer Timeline Activity</NuxtLink></li>
      <li><NuxtLink to="/features/crmTriggers">CRM-based Triggers</NuxtLink></li>
      <li><NuxtLink to="/features/custom">Custom</NuxtLink></li>
      <li><NuxtLink to="/features/customDash">Custom Dashboards</NuxtLink></li>
      <li><NuxtLink to="/features/customEmailDomain">Custom Email Domain</NuxtLink></li>
      <li><NuxtLink to="/features/customerPortal">Customer Portal</NuxtLink></li>
      <li><NuxtLink to="/features/customerProfiles">Customer Profiles</NuxtLink></li>
      <li><NuxtLink to="/features/customInputs">Custom Input Fields</NuxtLink></li>
      <li><NuxtLink to="/features/customSSO">Custom SSO</NuxtLink></li>
      <li><NuxtLink to="/features/dataExport">Data Export</NuxtLink></li>
      <li><NuxtLink to="/features/dataRemoval">Data removal</NuxtLink></li>
      <li><NuxtLink to="/features/debugMode">Debug Mode</NuxtLink></li>
      <li><NuxtLink to="/features/desktopApps">Desktop Apps</NuxtLink></li>
      <li><NuxtLink to="/features/developerApis">Developer APIs</NuxtLink></li>
      <li><NuxtLink to="/features/dpa">Data Processing Agreement</NuxtLink></li>
      <li><NuxtLink to="/features/email">Email</NuxtLink></li>
      <li><NuxtLink to="/features/embedApps">Embed Apps</NuxtLink></li>
      <li><NuxtLink to="/features/embeddedApps">Embedded Apps</NuxtLink></li>
      <li><NuxtLink to="/features/entities">Entities</NuxtLink></li>
      <li><NuxtLink to="/features/fileSharing">File Sharing</NuxtLink></li>
      <li><NuxtLink to="/features/filters">Filters</NuxtLink></li>
      <li><NuxtLink to="/features/flows">Flows</NuxtLink></li>
      <li><NuxtLink to="/features/followups">Follow-up Reminders</NuxtLink></li>
      <li><NuxtLink to="/features/freeTrial">Free Trial</NuxtLink></li>
      <li><NuxtLink to="/features/freshdesk">Freshdesk</NuxtLink></li>
      <li><NuxtLink to="/features/fullHistory">Full Conversations' history</NuxtLink></li>
      <li><NuxtLink to="/features/gDPRCompliance">GDPR Compliance</NuxtLink></li>
      <li><NuxtLink to="/features/hcArticles">Articles & Categories</NuxtLink></li>
      <li><NuxtLink to="/features/hcCustomization">Customization</NuxtLink></li>
      <li><NuxtLink to="/features/hcDomain">Custom Domain Name</NuxtLink></li>
      <li><NuxtLink to="/features/hcFeedback">Article Feedback</NuxtLink></li>
      <li><NuxtLink to="/features/hcMultilingual">Multilingual Help Center</NuxtLink></li>
      <li><NuxtLink to="/features/hcSdk">Help Center SDK</NuxtLink></li>
      <li><NuxtLink to="/features/hcSearch">Search</NuxtLink></li>
      <li><NuxtLink to="/features/hcSeo">Sitemap & SEO Meta Data</NuxtLink></li>
      <li><NuxtLink to="/features/helpDesk">HelpDesk</NuxtLink></li>
      <li><NuxtLink to="/features/helpWidget">Help Widget</NuxtLink></li>
      <li><NuxtLink to="/features/hubspot">HubSpot</NuxtLink></li>
      <li><NuxtLink to="/features/hybridTicketStream">Hybrid Ticket Stream</NuxtLink></li>
      <li><NuxtLink to="/features/iframes">Iframes</NuxtLink></li>
      <li><NuxtLink to="/features/instagram">Instagram</NuxtLink></li>
      <li><NuxtLink to="/features/interactionsPopularity">Interactions Popularity</NuxtLink></li>
      <li><NuxtLink to="/features/internalChat">Internal Agent Chat</NuxtLink></li>
      <li><NuxtLink to="/features/internalCopilot">Internal AI Copilot</NuxtLink></li>
      <li><NuxtLink to="/features/internalNotes">Internal Notes</NuxtLink></li>
      <li><NuxtLink to="/features/javascriptAPI">Javascript API</NuxtLink></li>
      <li><NuxtLink to="/features/keywordTriggers">Keyword-based Triggers</NuxtLink></li>
      <li><NuxtLink to="/features/line">Line</NuxtLink></li>
      <li><NuxtLink to="/features/liveChat">LiveChat</NuxtLink></li>
      <li><NuxtLink to="/features/liveMap">Live Geolocation Map</NuxtLink></li>
      <li><NuxtLink to="/features/liveTranslate">Live Translate</NuxtLink></li>
      <li><NuxtLink to="/features/liveTyping">Live Typing preview</NuxtLink></li>
      <li><NuxtLink to="/features/magicBrowse">Magic Browse</NuxtLink></li>
      <li><NuxtLink to="/features/make">Make</NuxtLink></li>
      <li><NuxtLink to="/features/maxQueueAutoHide">Max Queue Auto-hide/Auto-offline</NuxtLink></li>
      <li><NuxtLink to="/features/mcpServer">MCP Server</NuxtLink></li>
      <li><NuxtLink to="/features/messenger">Messenger</NuxtLink></li>
      <li><NuxtLink to="/features/mfa">Double-Factor Authentication</NuxtLink></li>
      <li><NuxtLink to="/features/mobileApps">Mobile Apps</NuxtLink></li>
      <li><NuxtLink to="/features/multilingualAI">Multilingual AI</NuxtLink></li>
      <li><NuxtLink to="/features/multilingualAIb">Multilingual AIb</NuxtLink></li>
      <li><NuxtLink to="/features/multilingualWidget">Multilingual Chat Widget</NuxtLink></li>
      <li><NuxtLink to="/features/n8n">n8n</NuxtLink></li>
      <li><NuxtLink to="/features/noCodeBuilder">No-code AI Chatbot Builder</NuxtLink></li>
      <li><NuxtLink to="/features/nodeMonitoring">Node Monitoring</NuxtLink></li>
      <li><NuxtLink to="/features/paidChats">Paid chats</NuxtLink></li>
      <li><NuxtLink to="/features/phone">Phone</NuxtLink></li>
      <li><NuxtLink to="/features/pipedrive">Pipedrive</NuxtLink></li>
      <li><NuxtLink to="/features/planPrice">Plan Price (per month)</NuxtLink></li>
      <li><NuxtLink to="/features/prebuiltAnalytics">Prebuilt Analytics</NuxtLink></li>
      <li><NuxtLink to="/features/prestashop">Prestashop</NuxtLink></li>
      <li><NuxtLink to="/features/priorityRouting">Priority Routing</NuxtLink></li>
      <li><NuxtLink to="/features/proactive">Proactive Chat Messages</NuxtLink></li>
      <li><NuxtLink to="/features/randomRouting">Random Routing</NuxtLink></li>
      <li><NuxtLink to="/features/ratings">Conversation Ratings</NuxtLink></li>
      <li><NuxtLink to="/features/realtimeNotif">Real-time Notifications</NuxtLink></li>
      <li><NuxtLink to="/features/restapi">REST API</NuxtLink></li>
      <li><NuxtLink to="/features/ringToAllRouting">Ring-to-all Routing</NuxtLink></li>
      <li><NuxtLink to="/features/roundRobin">Round-robin Routing</NuxtLink></li>
      <li><NuxtLink to="/features/salesforce">Salesforce</NuxtLink></li>
      <li><NuxtLink to="/features/sandbox">Sandbox Environment</NuxtLink></li>
      <li><NuxtLink to="/features/scenarioDrafts">Scenario Drafts</NuxtLink></li>
      <li><NuxtLink to="/features/segment">Segment</NuxtLink></li>
      <li><NuxtLink to="/features/segments">Segments</NuxtLink></li>
      <li><NuxtLink to="/features/shopify">Shopify</NuxtLink></li>
      <li><NuxtLink to="/features/siteSearch">AI-Powered Site Search</NuxtLink></li>
      <li><NuxtLink to="/features/slack">Slack</NuxtLink></li>
      <li><NuxtLink to="/features/sms">SMS</NuxtLink></li>
      <li><NuxtLink to="/features/squarespace">Squarespace</NuxtLink></li>
      <li><NuxtLink to="/features/sSO(Google,Microsoft,Apple)">SSO (Google, Microsoft, Apple)</NuxtLink></li>
      <li><NuxtLink to="/features/statusAnnouncement">Announcement</NuxtLink></li>
      <li><NuxtLink to="/features/statusCustomization">Customization</NuxtLink></li>
      <li><NuxtLink to="/features/statusNotif">Notifications</NuxtLink></li>
      <li><NuxtLink to="/features/straightStart">Straight-forward Start</NuxtLink></li>
      <li><NuxtLink to="/features/stripe">Stripe</NuxtLink></li>
      <li><NuxtLink to="/features/summary">Conversation Summary</NuxtLink></li>
      <li><NuxtLink to="/features/tags">Tags</NuxtLink></li>
      <li><NuxtLink to="/features/teamcollaboration">Team Collaboration</NuxtLink></li>
      <li><NuxtLink to="/features/telegram">Telegram</NuxtLink></li>
      <li><NuxtLink to="/features/templates">Templates</NuxtLink></li>
      <li><NuxtLink to="/features/templatesLibrary">Templates Library</NuxtLink></li>
      <li><NuxtLink to="/features/testingTool">Testing tool</NuxtLink></li>
      <li><NuxtLink to="/features/tls">TLS Encryption</NuxtLink></li>
      <li><NuxtLink to="/features/trainingHistory">Training History</NuxtLink></li>
      <li><NuxtLink to="/features/transcript">Conversation Transcript</NuxtLink></li>
      <li><NuxtLink to="/features/triage">Conversation Triage</NuxtLink></li>
      <li><NuxtLink to="/features/typingIndicator">Typing Status Indicator</NuxtLink></li>
      <li><NuxtLink to="/features/universalInbox">Universal Inbox</NuxtLink></li>
      <li><NuxtLink to="/features/unlimitedConvos">Unlimited Conversations</NuxtLink></li>
      <li><NuxtLink to="/features/unlimitedTemplates">Unlimited AI Chatbot Templates</NuxtLink></li>
      <li><NuxtLink to="/features/userExport">User export</NuxtLink></li>
      <li><NuxtLink to="/features/userManagement">User management</NuxtLink></li>
      <li><NuxtLink to="/features/utilizationRouting">Utilization-based Routing</NuxtLink></li>
      <li><NuxtLink to="/features/versionHistory">Version History</NuxtLink></li>
      <li><NuxtLink to="/features/viber">Viber</NuxtLink></li>
      <li><NuxtLink to="/features/visitorCurrentUrl">Visitor Current URL Tracking</NuxtLink></li>
      <li><NuxtLink to="/features/visualBuilder">Visual Builder</NuxtLink></li>
      <li><NuxtLink to="/features/voiceToText">Voice-to-text</NuxtLink></li>
      <li><NuxtLink to="/features/webflow">Webflow</NuxtLink></li>
      <li><NuxtLink to="/features/webhooks">Webhook Actions</NuxtLink></li>
      <li><NuxtLink to="/features/webhooks">Webhook Actions</NuxtLink></li>
      <li><NuxtLink to="/features/websiteMonitoring">Website Monitoring</NuxtLink></li>
      <li><NuxtLink to="/features/whatsappBiz">WhatsApp Business</NuxtLink></li>
      <li><NuxtLink to="/features/whiteLabel">White Label</NuxtLink></li>
      <li><NuxtLink to="/features/widgetCustomization">Widget Customization</NuxtLink></li>
      <li><NuxtLink to="/features/wix">Wix</NuxtLink></li>
      <li><NuxtLink to="/features/woocommerce">WooCommerce</NuxtLink></li>
      <li><NuxtLink to="/features/wordpress">WordPress</NuxtLink></li>
      <li><NuxtLink to="/features/workingHours">Working Hours Settings</NuxtLink></li>
      <li><NuxtLink to="/features/xTwitter">X (Twitter)</NuxtLink></li>
      <li><NuxtLink to="/features/zapier">Zapier</NuxtLink></li>
      <li><NuxtLink to="/features/zendesk">Zendesk</NuxtLink></li>
      <li><NuxtLink to="/features/zoho">Zoho CRM</NuxtLink></li>
    </ul>
  </section>
</template>

<script setup lang="ts">
useSeoMeta({ title: 'All features' });
</script>
